image: node:latest

include:
  - template: Code-Quality.gitlab-ci.yml

stages:
  - build
  - test
  - deploy

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build
  script:
    - npm install --progress=false
  artifacts:
    paths:
      - node_modules/

testing_testing:
  stage: test
  script: npm test

code_quality:
  artifacts:
    paths: [gl-code-quality-report.json]

pages:
  stage: deploy
  script:
    - npm install
    - npm run build
    - rm -rf public
    - mv build public
  artifacts:
    paths:
    - public
  only:
  - develop
